/**
 * generationAdapter — clean provider interface for ATOM Content generation.
 *
 *   demo       → deterministic, on-brand, clearly-labeled output (no API key)
 *   anthropic  → Claude via @anthropic-ai/sdk (ANTHROPIC_API_KEY)
 *   openai     → OpenAI chat completions (OPENAI_API_KEY)
 *   perplexity → Perplexity chat completions (PERPLEXITY_API_KEY)
 *
 * Provider is selected by ATOM_CONTENT_PROVIDER, else auto-detected from the
 * available keys, else falls back to "demo". No secret ever reaches the client.
 */
import Anthropic from "@anthropic-ai/sdk";
import type { ContentBrief } from "@shared/schema";
import type { LiveMetric } from "./liveNumbersEngine";
import { SYSTEM_PROMPT, buildUserPrompt, CONTENT_TYPE_LABELS } from "./promptBuilder";

export type ProviderName = "demo" | "anthropic" | "openai" | "perplexity";

export interface GenerationEnvelope {
  title: string;
  asset_type: string;
  content: string;
  summary: string;
  cta: string;
  live_numbers_used: Array<{ metric_key: string; label: string; value: string; source: string }>;
  claims: string[];
  claims_needing_verification: string[];
  voice_compliance_notes: string[];
  risk_flags: string[];
  derivative_recommendations: string[];
}

export interface GenerationContext {
  brief: ContentBrief;
  voiceYaml: string;
  usableMetrics: LiveMetric[];
  suggestableMetrics: LiveMetric[];
  hasUsable: boolean;
}

export interface ProviderFallback {
  /** The provider that was requested/resolved before it failed. */
  requestedProvider: ProviderName;
  reason: string;
}

export interface GenerationResult {
  provider: ProviderName;
  envelope: GenerationEnvelope;
  isDemo: boolean;
  /** Set when a production provider failed and we degraded to demo output. */
  fallback: ProviderFallback | null;
}

function clean(v?: string): string {
  return (v || "").replace(/\\n/g, "").trim();
}

export function resolveProvider(): ProviderName {
  const forced = clean(process.env.ATOM_CONTENT_PROVIDER).toLowerCase();
  if (forced === "demo" || forced === "anthropic" || forced === "openai" || forced === "perplexity") {
    return forced;
  }
  if (clean(process.env.ANTHROPIC_API_KEY)) return "anthropic";
  if (clean(process.env.OPENAI_API_KEY)) return "openai";
  if (clean(process.env.PERPLEXITY_API_KEY)) return "perplexity";
  return "demo";
}

function extractJson(text: string): GenerationEnvelope {
  const fenced = text.replace(/```json\n?/gi, "").replace(/```\n?/g, "").trim();
  const candidate = fenced.match(/\{[\s\S]*\}/)?.[0] ?? fenced;
  const parsed = JSON.parse(candidate);
  return normalizeEnvelope(parsed);
}

function normalizeEnvelope(e: any): GenerationEnvelope {
  const arr = (x: any): any[] => (Array.isArray(x) ? x : []);
  return {
    title: String(e.title || "Untitled"),
    asset_type: String(e.asset_type || ""),
    content: String(e.content || ""),
    summary: String(e.summary || ""),
    cta: String(e.cta || ""),
    live_numbers_used: arr(e.live_numbers_used).map((m: any) => ({
      metric_key: String(m.metric_key || m.metricKey || ""),
      label: String(m.label || ""),
      value: String(m.value || ""),
      source: String(m.source || ""),
    })),
    claims: arr(e.claims).map(String),
    claims_needing_verification: arr(e.claims_needing_verification).map(String),
    voice_compliance_notes: arr(e.voice_compliance_notes).map(String),
    risk_flags: arr(e.risk_flags).map(String),
    derivative_recommendations: arr(e.derivative_recommendations).map(String),
  };
}

// ── DEMO PROVIDER ────────────────────────────────────────────────────────────
// Deterministic, on-brand output. Clearly labels itself as demo and uses ONLY
// the verified metrics it was handed (never invents numbers).
function demoGenerate(ctx: GenerationContext): GenerationEnvelope {
  const { brief, usableMetrics, hasUsable } = ctx;
  const typeLabel = CONTENT_TYPE_LABELS[brief.contentType] || brief.contentType;
  const cta = brief.primaryCta || "Book a live walkthrough.";
  const focus = brief.productFocus || "ATOM Sales OS";

  const proofLine = hasUsable
    ? usableMetrics.slice(0, 3).map((m) => `${m.metricLabel.toLowerCase()} ${m.display}`).join(", ")
    : null;

  const intensityOpener: Record<string, string> = {
    calm: "Most revenue teams don't have a tooling problem. They have an execution gap.",
    sharp: "Your team doesn't need another dashboard. It needs to close more, faster.",
    war_mode: "While your competitors stare at dashboards, their pipeline goes cold. Yours shouldn't.",
  };

  const body = [
    `> **[DEMO OUTPUT]** Generated by the ATOM Content demo provider. Wire an API key (ANTHROPIC / OPENAI / PERPLEXITY) for production drafts.`,
    "",
    `# ${brief.title}`,
    "",
    intensityOpener[brief.intensity] || intensityOpener.sharp,
    "",
    `${focus} is a revenue command center — autonomous sales execution that turns signal into sale while your team focuses on the calls that close.`,
    "",
    `**The cost of inaction is quiet but real.** Every untouched signal is a deal your competitor works first. Dashboards report the loss. They don't prevent it.`,
    "",
    proofLine
      ? `In recent product activity, ATOM drove ${proofLine}. Each number is pulled from verified product activity — not a brochure.`
      : `We're not citing numbers here: no verified live metrics are attached to this draft, and ATOM Content does not invent proof. Numeric claims will be added once verified activity is available.`,
    "",
    `**What changes for ${brief.targetAudience}:** less manual follow-up, faster signal-to-sale, and an execution layer that runs while your team sleeps.`,
    "",
    `**${cta}**`,
  ].join("\n");

  const liveUsed = hasUsable
    ? usableMetrics.slice(0, 3).map((m) => ({
        metric_key: m.metricKey,
        label: m.metricLabel,
        value: m.display,
        source: m.sourceSystem,
      }))
    : [];

  return {
    title: brief.title,
    asset_type: typeLabel,
    content: body,
    summary: `Demo ${typeLabel.toLowerCase()} for ${brief.targetAudience} at the ${brief.funnelStage} stage, positioning ${focus} as an execution layer over dashboards.`,
    cta,
    live_numbers_used: liveUsed,
    claims: hasUsable ? usableMetrics.slice(0, 3).map((m) => `${m.metricLabel}: ${m.display}`) : [],
    claims_needing_verification: [],
    voice_compliance_notes: [
      "Demo output is pre-shaped to the ATOM command voice.",
      "No banned phrases used; leads with business impact.",
    ],
    risk_flags: hasUsable ? [] : ["No verified metrics available — numeric claims omitted by design."],
    derivative_recommendations:
      brief.contentType === "blog"
        ? ["LinkedIn post", "X thread", "YouTube description"]
        : ["LinkedIn post"],
  };
}

// ── ANTHROPIC PROVIDER ───────────────────────────────────────────────────────
async function anthropicGenerate(ctx: GenerationContext): Promise<GenerationEnvelope> {
  const client = new Anthropic();
  const userPrompt = buildUserPrompt(ctx);
  const msg = await client.messages.create({
    model: "claude_sonnet_4_6",
    max_tokens: 4000,
    system: SYSTEM_PROMPT,
    messages: [{ role: "user", content: userPrompt }],
  });
  const text = (msg.content as any[]).find((b) => b.type === "text")?.text || "{}";
  return extractJson(text);
}

// ── OPENAI PROVIDER ──────────────────────────────────────────────────────────
async function openaiGenerate(ctx: GenerationContext): Promise<GenerationEnvelope> {
  const key = clean(process.env.OPENAI_API_KEY);
  const model = clean(process.env.OPENAI_MODEL) || "gpt-4o";
  const res = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` },
    body: JSON.stringify({
      model,
      max_tokens: 4000,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: buildUserPrompt(ctx) },
      ],
    }),
  });
  if (!res.ok) throw new Error(`OpenAI error ${res.status}: ${await res.text()}`);
  const data: any = await res.json();
  return extractJson(data.choices?.[0]?.message?.content || "{}");
}

// ── PERPLEXITY PROVIDER ──────────────────────────────────────────────────────
async function perplexityGenerate(ctx: GenerationContext): Promise<GenerationEnvelope> {
  const key = clean(process.env.PERPLEXITY_API_KEY);
  const model = clean(process.env.PERPLEXITY_MODEL) || "sonar-pro";
  const res = await fetch("https://api.perplexity.ai/chat/completions", {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` },
    body: JSON.stringify({
      model,
      max_tokens: 4000,
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: buildUserPrompt(ctx) },
      ],
    }),
  });
  if (!res.ok) throw new Error(`Perplexity error ${res.status}: ${await res.text()}`);
  const data: any = await res.json();
  return extractJson(data.choices?.[0]?.message?.content || "{}");
}

export async function generateContent(ctx: GenerationContext): Promise<GenerationResult> {
  const provider = resolveProvider();
  try {
    if (provider === "anthropic") return { provider, envelope: await anthropicGenerate(ctx), isDemo: false, fallback: null };
    if (provider === "openai") return { provider, envelope: await openaiGenerate(ctx), isDemo: false, fallback: null };
    if (provider === "perplexity") return { provider, envelope: await perplexityGenerate(ctx), isDemo: false, fallback: null };
  } catch (err: any) {
    // Production provider failed — fall back to demo so the worker never hard-fails,
    // but make the degradation explicit (risk flag + structured fallback) so the
    // caller, evidence panel, and UI can surface it instead of silently shipping
    // demo output behind an HTTP 200.
    const reason = `Provider "${provider}" failed (${err.message || "unknown error"}); fell back to demo output.`;
    const env = demoGenerate(ctx);
    env.risk_flags.unshift(reason);
    return { provider: "demo", envelope: env, isDemo: true, fallback: { requestedProvider: provider, reason } };
  }
  return { provider: "demo", envelope: demoGenerate(ctx), isDemo: true, fallback: null };
}

// ── DERIVATIVE + REFINE ──────────────────────────────────────────────────────
// Reuse the same provider machinery with a transform instruction layered on
// top of the source asset.
export async function transformContent(args: {
  instruction: string;
  sourceContent: string;
  voiceYaml: string;
  usableMetrics: LiveMetric[];
}): Promise<{ provider: ProviderName; content: string; isDemo: boolean; fallback: ProviderFallback | null }> {
  const provider = resolveProvider();
  const sys = SYSTEM_PROMPT;
  const user = `${args.instruction}

You must obey this voice profile:
\`\`\`yaml
${args.voiceYaml}
\`\`\`

You may ONLY use these verified metrics as factual numbers (omit numbers if none apply):
${args.usableMetrics.length ? args.usableMetrics.map((m) => `- ${m.metricLabel}: ${m.display} (${m.sourceSystem}, ${m.confidence})`).join("\n") : "- (none available — do not invent numbers)"}

SOURCE ASSET:
"""
${args.sourceContent}
"""

Return ONLY the rewritten/derived asset body in markdown. No preamble, no JSON.`;

  try {
    if (provider === "anthropic") {
      const client = new Anthropic();
      const msg = await client.messages.create({
        model: "claude_sonnet_4_6",
        max_tokens: 3000,
        system: sys,
        messages: [{ role: "user", content: user }],
      });
      const text = (msg.content as any[]).find((b) => b.type === "text")?.text || "";
      return { provider, content: text.trim(), isDemo: false, fallback: null };
    }
    if (provider === "openai") {
      const key = clean(process.env.OPENAI_API_KEY);
      const res = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` },
        body: JSON.stringify({ model: clean(process.env.OPENAI_MODEL) || "gpt-4o", max_tokens: 3000, messages: [{ role: "system", content: sys }, { role: "user", content: user }] }),
      });
      if (!res.ok) throw new Error(`OpenAI error ${res.status}`);
      const data: any = await res.json();
      return { provider, content: (data.choices?.[0]?.message?.content || "").trim(), isDemo: false, fallback: null };
    }
    if (provider === "perplexity") {
      const key = clean(process.env.PERPLEXITY_API_KEY);
      const res = await fetch("https://api.perplexity.ai/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` },
        body: JSON.stringify({ model: clean(process.env.PERPLEXITY_MODEL) || "sonar-pro", max_tokens: 3000, messages: [{ role: "system", content: sys }, { role: "user", content: user }] }),
      });
      if (!res.ok) throw new Error(`Perplexity error ${res.status}`);
      const data: any = await res.json();
      return { provider, content: (data.choices?.[0]?.message?.content || "").trim(), isDemo: false, fallback: null };
    }
  } catch (err: any) {
    if (provider !== "demo") {
      // Production transform failed — degrade to a labeled demo transform but
      // make the degradation explicit instead of silently returning HTTP 200.
      const reason = `Provider "${provider}" failed during transform (${err?.message || "unknown error"}); returned demo transform.`;
      return {
        provider: "demo",
        isDemo: true,
        content: `> **[DEMO TRANSFORM — provider fallback]** ${reason}\n\n${args.sourceContent}`,
        fallback: { requestedProvider: provider, reason },
      };
    }
  }
  // Demo transform: append a labeled note rather than fabricate a rewrite.
  return {
    provider: "demo",
    isDemo: true,
    content: `> **[DEMO TRANSFORM]** ${args.instruction}\n\n${args.sourceContent}`,
    fallback: null,
  };
}
