import type { VercelRequest, VercelResponse } from "@vercel/node";

const PRODUCTS = [
  { id: 1, name: "Antimatter AI Platform", slug: "antimatter-ai", tagline: "Digital Solutions That Matter", description: "Full-service AI development, product design, and GTM strategy platform. End-to-end product design, scalable web/mobile development, production-ready AI systems, HIPAA-compliant healthcare apps, IoT systems, and data-driven go-to-market strategies — all under one roof.", url: "https://antimatterai.com", category: "platform", targetMarket: "Enterprise organizations, SaaS companies, startups, healthcare systems, IoT companies needing AI-powered product development and go-to-market execution", keyFeatures: JSON.stringify(["End-to-end product design (User Research, UX Flows, UI Systems, Design Ops)","Full-stack development (React/Next frontends, Node backend APIs, Flutter mobile, Docker CI/CD)","AI Development (LLM agents, RAG, fine-tuning, model evals, guardrails, vision/NLP/speech pipelines)","GTM Strategy (ICP & segmentation, positioning & messaging, pricing & packaging, demand gen)","Healthcare Apps (HIPAA/PHI compliance, telehealth, EHR integrations via FHIR/HL7, audit logging)","IoT Development (embedded firmware, BLE/Zigbee/LoRa, MQTT ingestion, edge AI, OTA pipelines)"]), valueProps: JSON.stringify(["20+ projects delivered with 100% client satisfaction","Full-stack capability: design → engineering → AI → GTM under one roof","AI-native approach — every solution leverages ML from day one","24/7 support with dedicated teams","Proven case studies: Clinix AI, OWASP Foundation, Synergies4, Curehire"]), commonObjections: JSON.stringify(["We already have an in-house dev team","AI development is too expensive","We're not ready for AI yet","How do we know your AI will work?","We've been burned by agencies before"]), competitiveEdge: "Unlike traditional agencies, Antimatter AI is AI-native — every solution leverages machine learning from day one. We combine product design, engineering, AI development, healthcare compliance, IoT, and GTM under one roof, eliminating handoff friction and accelerating time-to-market by 3-5x.", icon: "Atom" },
  { id: 2, name: "ATOM Enterprise AI", slug: "atom-enterprise", tagline: "Enterprise AI Framework — Deploy Anywhere, Own Everything", description: "ATOM is Antimatter's enterprise AI deployment framework. Deploy voice, search, and workflow agents in controlled environments — VPC, on-prem, or edge — with governance, zero-training guarantees, and full IP ownership. Powered by Akamai + Linode edge partnership.", url: "https://www.antimatterai.com/enterprise-ai", category: "enterprise-ai", targetMarket: "CIOs, CTOs, VP Engineering at regulated enterprises, financial services, healthcare systems, defense contractors, government agencies, Fortune 500", keyFeatures: JSON.stringify(["Deploy anywhere: VPC, on-prem, hybrid, edge, containers, Kubernetes","Security & Compliance: encryption at rest/transit, SSO + RBAC, audit logs, zero-training, private networking","Full IP Ownership: you own prompts, agents, workflows, outputs — hard isolation, no shared pools","Composable Framework: agents, orchestration, tool calls, retrieval, deterministic UI modules","Model-Agnostic Runtime: swap hosted, open-source, private, or on-prem models without code changes","Edge Deployment: Akamai + Linode partnership for low-latency voice/real-time UX"]), valueProps: JSON.stringify(["Deploy agentic AI in your environment — not someone else's cloud","Zero-training guarantee: ATOM never trains on your data or resells metadata","Swap model providers without changing product logic — no vendor lock-in","RBAC, audit trails, encryption, and retention policies per environment","Edge inference with hybrid routing via Akamai","Composable system: reuse agents, retrieval, and tools across teams"]), commonObjections: JSON.stringify(["We already have our own AI infrastructure","Enterprise AI frameworks are too complex","We're locked into our current cloud provider","How is this different from AWS Bedrock or Azure AI?","Our compliance team won't approve another vendor"]), competitiveEdge: "ATOM is a framework, not a tool — composable AI systems for voice, search, workflows that you fully own. Unlike Kore.ai, Intercom Fin, or Microsoft Copilot Studio, ATOM offers hard tenant isolation, zero-training guarantees, full IP ownership, and deploys to VPC/on-prem/edge.", icon: "Server" },
  { id: 3, name: "Vidzee", slug: "vidzee", tagline: "Listing Photos to Cinematic Videos", description: "AI-powered platform that transforms real estate listing photos into cinematic property videos in under 5 minutes.", url: "https://vidzee.vercel.app", category: "real-estate", targetMarket: "Real estate agents, brokerages, property managers, luxury agents, team leads", keyFeatures: JSON.stringify(["AI-powered storyboarding (room detection, scene ordering, best-shot selection)","Cinematic video generation powered by Kling AI","Multi-format export (9:16 for Reels/TikTok, 16:9 for YouTube/MLS)","3 style packs: Modern Clean, Luxury Classic, Bold Dynamic","Custom branding, team accounts, API access, white-label exports"]), valueProps: JSON.stringify(["Create cinematic listing videos in under 5 minutes","Save $200-$500 per video vs. hiring a videographer","12,400+ videos created by 2,800+ agents","One upload yields two formats for all platforms"]), commonObjections: JSON.stringify(["I already hire a videographer","AI videos won't look professional enough","My listings don't need video","Free plan seems too limited"]), competitiveEdge: "Vidzee replaces the $200-$500/video cost of a videographer with AI that produces cinematic results in 5 minutes.", icon: "Video" },
  { id: 4, name: "Clinix Agent", slug: "clinix-agent", tagline: "Supervised AI Billing Operations", description: "All-in-one platform helping healthcare providers recover lost revenue by automating insurance denial appeals and resubmissions.", url: "https://www.clinixagent.com", category: "healthcare", targetMarket: "Healthcare providers, hospitals, billing teams, RCM teams", keyFeatures: JSON.stringify(["Eligibility Guardrails (plan rules, copay, prior-auth warnings)","Clean Claim Engine (payer-aware modifiers, POS validation, ICD↔CPT pointers)","Live Status + Remits (276/277 real-time acceptance, 835 parsing)","Appeal Intelligence (template attachments, track overturn rates)","HIPAA-grade security (E2E encryption, RLS, audit trails)","Success-based pricing (0.6-1.2% paid claims, 5-12% recovery)"]), valueProps: JSON.stringify(["Stop denials before they start with eligibility guardrails","Auto-generate corrections and appeal packets","Track claim status and recovery with real-time reporting","Pay only on success — aligned incentives"]), commonObjections: JSON.stringify(["We already have a billing team","We're worried about HIPAA compliance","Our denial rate is manageable","We don't trust AI with patient data"]), competitiveEdge: "Clinix Agent combines Stedi rails with payer-specific rules and ML signals — success-based pricing means you only pay when we recover revenue.", icon: "ShieldCheck" },
  { id: 5, name: "Clinix AI", slug: "clinix-ai", tagline: "AI-Powered Healthcare Documentation Automation", description: "AI-driven automation for medical documentation, SOAP notes, billing, and claims management. Generates ICD-10, CPT, and DSM-5-TR codes.", url: "https://www.tryclinixai.com", category: "healthcare", targetMarket: "Healthcare providers, clinicians, medical practices, behavioral health providers", keyFeatures: JSON.stringify(["AI-powered SOAP note automation","ICD-10, CPT, and DSM-5-TR code generation","Seamless EHR integration","Real-time clinical workflow management","Diagnosis extraction and procedure justification"]), valueProps: JSON.stringify(["Cut documentation time by 70%","Accurate AI-generated coding reduces claim denials","Seamless integration with existing EHR systems","Reduce administrative burden and burnout"]), commonObjections: JSON.stringify(["AI can't capture clinical nuance","We're comfortable with our current workflow","What about coding accuracy?","EHR integration is always a nightmare"]), competitiveEdge: "Clinix AI understands clinical context — extracts diagnoses and generates accurate ICD-10/CPT/DSM-5-TR codes in real-time. Providers save 2-3 hours per day.", icon: "Stethoscope" },
  { id: 6, name: "Red Team ATOM", slug: "red-team-atom", tagline: "Autonomous Quantum-Ready Red Team Range", description: "Active adversarial simulation platform with post-quantum cryptography engine, AI & quantum attack telemetry, and MITRE ATLAS heatmaps.", url: "https://red-team-atom.vercel.app", category: "cybersecurity", targetMarket: "CISOs, security teams, defense contractors, government agencies, Fortune 500", keyFeatures: JSON.stringify(["PQC Engine (lattice-based key rotation, harvest-now-decrypt-later safe)","AI & Quantum Attack Telemetry (real-time)","Threat Analytics (Critical, High, Model Attacks, Prompt Inject)","MITRE ATLAS & Quantum Technique Heatmap","Agent-level, model attack, and quantum threat filters"]), valueProps: JSON.stringify(["Only autonomous red team platform that's quantum-ready","Proactively defend against harvest-now-decrypt-later attacks","Real-time AI and quantum attack telemetry","MITRE ATLAS compliance mapping out of the box"]), commonObjections: JSON.stringify(["Quantum threats are years away","We already do annual penetration testing","Our team doesn't have quantum security expertise","This seems too advanced for our current needs"]), competitiveEdge: "Red Team ATOM is the industry's first autonomous, quantum-ready red team range with continuous adversarial simulations, PQC-grade key rotation, and MITRE ATLAS heatmapping.", icon: "Shield" }
];

export default function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== "GET") return res.status(405).json({ error: "Method not allowed" });

  const { slug } = req.query;
  if (slug && typeof slug === "string") {
    const product = PRODUCTS.find(p => p.slug === slug);
    if (!product) return res.status(404).json({ error: "Product not found" });
    return res.json(product);
  }

  return res.json(PRODUCTS);
}
